h=int(input("enter the value of height"))
b=int(input("enter the value of base"))
triangle=lambda h,b:(.5*h*b)
print("Area of a triangle: ",triangle(h,b))
a=int(input("enter the value for squareside: "))
square=lambda a: (a*a)
print("Area of a square: ",square(a))
b=int(input("enter the value of base"))
l=int(input("enter the value of lenght"))
rectangle=lambda b,l:(l*b)
print("Area of a rectangle :",rectangle(l,b))
